version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-article-local
    environment:
      MYSQL_ROOT_PASSWORD: adminroot
      # Root password
      MYSQL_DATABASE: article
      # Default database (optional)
      MYSQL_USER: user
      # Custom username
      MYSQL_PASSWORD: admin
      # Custom password for that user
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: >
      --gtid_mode=ON
      --enforce_gtid_consistency=ON
      --log_bin=binlog
      --binlog_format=ROW
      --server-id=1
      --binlog_row_image=FULL
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padminroot"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql-data:
